# Generated by Django 5.1.5 on 2025-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
