# Generated by Django 5.1.5 on 2025-03-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_marketplace_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='color',
            field=models.CharField(default='#d1d1d1', max_length=7),
        ),
    ]
