# Generated by Django 5.1.5 on 2025-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0003_marketplace_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='logo_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
