# Generated by Django 5.1.5 on 2025-02-16 15:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_phone', models.CharField(max_length=20)),
                ('bill_email', models.EmailField(max_length=255)),
                ('bill_firstname', models.CharField(max_length=50)),
                ('bill_lastname', models.CharField(max_length=50)),
                ('bill_company', models.CharField(blank=True, default='', max_length=100)),
                ('bill_address', models.CharField(max_length=255)),
                ('bill_city', models.CharField(max_length=100)),
                ('bill_zipcode', models.CharField(max_length=20)),
                ('bill_country', models.PositiveSmallIntegerField(choices=[(0, 'Spain'), (1, 'France')])),
                ('ship_phone', models.CharField(max_length=20)),
                ('ship_email', models.EmailField(max_length=255)),
                ('ship_firstname', models.CharField(max_length=50)),
                ('ship_lastname', models.CharField(max_length=50)),
                ('ship_company', models.CharField(blank=True, default='', max_length=100)),
                ('ship_address', models.CharField(max_length=255)),
                ('ship_city', models.CharField(max_length=100)),
                ('ship_zipcode', models.CharField(max_length=20)),
                ('ship_country', models.PositiveSmallIntegerField(choices=[(0, 'Spain'), (1, 'France')])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Processing'), (1, 'Pending'), (2, 'Preparing'), (3, 'Shipped'), (4, 'Refused'), (5, 'Canceled'), (6, 'Refunded')], default=0)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ticket', models.CharField(blank=True, default='', max_length=30)),
                ('ticket_refund', models.CharField(blank=True, default='', max_length=30)),
                ('pay_method', models.PositiveSmallIntegerField(choices=[(0, 'PayPal'), (1, 'Credit Card'), (2, 'Bank Transfer'), (3, 'Cash on Delivery'), (4, 'Bizum')])),
                ('package_quantity', models.PositiveSmallIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.carrier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplaces.marketplace')),
            ],
        ),
    ]
