# Generated by Django 5.1.5 on 2025-02-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='marketplace_product',
        ),
    ]
