# Generated by Django 5.1.5 on 2025-03-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
