# Generated by Django 5.1.5 on 2025-04-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productattributetype_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='data_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='data_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='data_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='data_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='data_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
